### ISSUE TITLE
AI: prozedural NavMesh generation

### ISSUE THREAD

**Issue by Kossinator** [kellergemeinde/game_towerdefense#103]
Wir generieren unser Spielfeld dynamisch. Bitte überprüfe ob `NavMesh-Daten` von Unity auch während der Laufzeit errechnet werden können. Funktionalitäten dafür sollten ab `Unity 2017` zur Verfügung stehen.

- [ ] Create a nav-mesh at runtime!

**Comment by bl4ck2909** [comment]
Useful:
https://github.com/Unity-Technologies/NavMeshComponents
