### ISSUE TITLE
Discord: Custom Icon with Reference to Pr0

### ISSUE THREAD

**Issue by ulfgebhardt** [kellergemeinde/game_towerdefense#111]
### Prerequisites
* [x] Feature Request

### Description
Make an Discord Icon for the Server not only referencing Gamedevelopment, but also reference the Origin of this Project the Pr0
 
[Current Image](https://cdn.discordapp.com/icons/388125051922284544/04daf453833ed65d51e119ea32ab7bc8.png)

**Comment by Hirudo89** [comment]
![wip](https://user-images.githubusercontent.com/29264609/36701145-9703f342-1b52-11e8-98fb-245b5398dc7f.png)
Modeling WIP, materials placeholders

**Comment by xdubx** [comment]
Push the raw file pls in the separat git repo.
