### ISSUE TITLE
3D - Unit concepts

### ISSUE THREAD

**Issue by Cek4y** [kellergemeinde/game_towerdefense#118]
We need a general overview over our units. 

- Create a unified artstyle, according to the latest GDD
- Model simple unit concepts (preferably in 3D), even if its just a few shapes
- Combine them in one image, provide descriptions if needed
- If you can, create a color palette or material previews

Units to create:
Worker
Archer
Soldier
Basic tower

**Comment by xdubx** [comment]
i create some sketchs for the units.

**Comment by PolishStealAway** [comment]
first time blender after some tutorials, tried to shape the fighter (ignore the "boots") 
[Fighter #1.zip](https://github.com/kellergemeinde/game_towerdefense/files/1641028/Fighter.1.zip)

**Comment by ulfgebhardt** [comment]
@Cek4y Review und Doku bitte

**Comment by Cek4y** [comment]
Took a different way, closed!
