### ISSUE TITLE
Basic NavMesh Implementation

### ISSUE THREAD

**Issue by bl4ck2909** [kellergemeinde/game_towerdefense#121]
### Description
Simple NavMesh Implementation

- [ ] Add needed fields to IMoveable (exp. Acceleration, TurningSpeed, ..)

- [x] Implement MoveTo() in one class

**Comment by ulfgebhardt** [comment]
@bl4ck2909 Wie siehts hier aus?

**Comment by bl4ck2909** [comment]
@ulfgebhardt Kann ich gleich fertig machen

**Comment by ulfgebhardt** [comment]
Super, Dank dir!
