### ISSUE TITLE
PlusRessource Always Collides

### ISSUE THREAD

**Issue by bl4ckl** [kellergemeinde/game_towerdefense#125]
### Prerequisites
* [ ] Feature Request
* [x] Bug

* [x] Are you running the latest version? (2017.3.0f3)

### Description
[Description of the bug or feature]
The Rigidbody of all PlusRessources collide all the time giving the game a CPU time of 50% on my PC even if nothing happens.

Find another way to spawn the resource without box collider or just disable it when everything is in place.

### Branch
* [x] Master

**Comment by janousch** [comment]
The mesh of the resource will be replaced with a particle effect.

**Comment by janousch** [comment]
[Update] The resource will be replaced by a mash without a rigidbody.

**Comment by xdubx** [comment]
[Update] Other spawn system
