### ISSUE TITLE
2D Concept: Worker

### ISSUE THREAD

**Issue by Cek4y** [kellergemeinde/game_towerdefense#127]
Please draw up a quick concept for our Worker unit like you did with the Soldier.

**Comment by ulfgebhardt** [comment]
@xdubx magst du das auch machen? Du machst das gut!

**Comment by xdubx** [comment]
![worker](https://user-images.githubusercontent.com/23421736/36632976-c92b4f58-198d-11e8-8cbd-50a451fd2f86.png)
