### ISSUE TITLE
2D Concept: Archer

### ISSUE THREAD

**Issue by Cek4y** [kellergemeinde/game_towerdefense#128]
Please draw up a quick concept for our Archer unit like you did with the Soldier.

**Comment by xdubx** [comment]
![archer](https://user-images.githubusercontent.com/23421736/36288633-facea7c2-12bb-11e8-9993-37fcedb177d2.png)

Can find at: https://github.com/xdubx/pictures/blob/master/archer.png

**Comment by ulfgebhardt** [comment]
@Cek4y Review und Doku bitte

**Comment by Cek4y** [comment]
Done, moving to 3D phase

**Comment by xdubx** [comment]
![bogen](https://user-images.githubusercontent.com/23421736/43489022-dd360e52-951b-11e8-8d54-765615807548.jpg)
