### ISSUE TITLE
2D Concept: Tower

### ISSUE THREAD

**Issue by Cek4y** [kellergemeinde/game_towerdefense#129]
Please draw up a quick concept for our Tower like you did with the Soldier.

**Comment by xdubx** [comment]
![tower](https://user-images.githubusercontent.com/23421736/36389574-be5f4daa-159f-11e8-9ca5-bdc4e7a9dfbb.png)

Found at: https://github.com/xdubx/pictures/blob/master/tower.png

**Comment by ulfgebhardt** [comment]
@Cek4y Review und Doku bitte

**Comment by Cek4y** [comment]
Done, moving to 3D phase
