### ISSUE TITLE
**Simple Art Assets**

### ISSUE THREAD

**Issue by janousch** [kellergemeinde/game_towerdefense#35]
Description 
Für unser Framework bräuchten wir einfache Art Assets. Um etwas anscahulicher zu sein.
Unter "einfach" versteht sich das es Lowpoly sein soll und eine Simple Textur erstellt wird.
Je weniger arbeit investiert wird desto besser.

Sehe Subtask für mehr informationen was benöttigt wird.

**Comment by 0dr** [comment]
I'd recommend using free assets from the store.
cons:
- not best loading time
- one would have to search   

pros:
- less work for everyone (those whom need one will find the best suited)
- large collection with textures, animations and shit

"/close ?

**Comment by Cek4y** [comment]
Closed, outdated!
