### ISSUE TITLE
Asset: 2D Einheiten - Soldat

### ISSUE THREAD

**Issue by janousch** [kellergemeinde/game_towerdefense#60]
Skizze erstellen zur Einheit Soldat

**Comment by xdubx** [comment]
[[https://github.com/xdubx/pictures/blob/master/soldat.png]]

**Comment by ulfgebhardt** [comment]
@Cek4y Review and Docu

**Comment by Cek4y** [comment]
Done, moving to 3D phase.

**Comment by xdubx** [comment]
![zeichenflache 1](https://user-images.githubusercontent.com/23421736/43369784-09f8b362-9374-11e8-9539-18ee6ec90fc2.png)
