### ISSUE TITLE
Input: Own event system.

### ISSUE THREAD

**Issue by Kossinator** [kellergemeinde/game_towerdefense#98]
Create a new event system for different unity ui-elements.

- [ ] Delegates as callback.
- [ ] Optional execution priorities.
- [ ] Examples as wiki entry.
- [ ] Event: OnClick
- [ ] Event: OnChange

Extras:
- [ ] Compatibility with the unity event system would be a big plus.

**Comment by hrkrx** [comment]
I like the idea of a full customizable EventSystem, but is it feasable with the limited resources we have?

What improvements in comparison to the inbuild Unity EventSystems are to be expected/desired?

And how should it be interfaced?

**Comment by xdubx** [comment]
Please add docu for other programmer

**Comment by hrkrx** [comment]
See Commit
